DROP DATABASE IF EXISTS cinema;
CREATE DATABASE IF NOT EXISTS cinema;

USE cinema;

CREATE TABLE IF NOT EXISTS sessao (
  id INT(11) NOT NULL AUTO_INCREMENT,
  sala INT(11) NOT NULL,
  filme INT(11) NOT NULL,
  data DATE NOT NULL,
  horaInicio TIME NOT NULL,
  capacidade INT(11) NOT NULL,
  PRIMARY KEY (id)
  );